## path to tools ##
samTools:  /path/to/samtools ## need to specify
bxTools:  /path/to/bxtools ## need to specify

## paths to scripts ##
molCov_script:  code/getMoleculeCoverage.R
phaseCounts_hetSites_script:  code/getPhasedHETSitesFromLLRVCF.R
phaseCounts_counts_script:  code/getTumourAlleleCountsAtHETSites.py
TitanCNA_rscript: code/titanCNA_v1.15.0_TenX.R
TitanCNA_selectSolutionRscript: code/selectSolution.R
TitanCNA_combineTitanIchorCNA:  code/combineTITAN-ichor.R
TitanCNA_libdir:  /path/to/TitanCNA/ ## optional
ichorCNA_libdir:  /path/to/ichorCNA/ ## optional

## reference settings ##
genomeBuild: hg38
genomeStyle:  UCSC
snpVCF:  /path/to/hapmap_3.3.hg38.vcf.gz ## optional
cytobandFile:  data/cytoBand_hg38.txt # only need if hg38
centromere:  data/GRCh38.GCA_000001405.2_centromere_acen.txt
sex:  male

## LongRanger params ##
bamFileName:  phased_possorted_bam.bam
phaseVariantFileName:  phased_variants.vcf.gz

## standard parameters for qsub memory, runtime, pe (parallel environment)
# use what your scheduler designates for parallel environment; does not apply to local run
# invoke using:
# snakemake -s TitanCNA.snakefile --cluster-sync "qsub -l h_vmem={params.mem},h_rt={params.runtime} {params.pe}" -j 200 --jobscript config/cluster.sh
std_mem:  4G
std_runtime:  "03:00:00" 
std_numCores:  -pe smp 1 -binding linear:1

## params for each step ##
## bxTools ##
bx_mapQual:  60
bx_bedFileRoot:  data/10kb_hg38/10kb_hg38

## molecule coverage ##
molCov_minReadsPerBX:  2
molCov_chrs:  c(1:22, \"X\")
molCov_gcWig: data/gc_hg38_10kb.wig
molCov_mapWig:  data/map_hg38_10kb.wig
molCov_maxCN:  8

## get HET sites from LongRanger phased variant VCF ##
het_minVCFQuality:  100
het_minDepth:  10
het_minVAF:  0.25
het_mem:  16G
het_runtime:  "06:00:00"

## bam filters for tumor allelic counts ##
het_minBaseQuality:  10
het_minMapQuality:  20

## TitanCNA params ##
TitanCNA_maxNumClonalClusters: 2
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit:  0.5
TitanCNA_maxPloidy:  3
TitanCNA_haplotypeBinSize: 1e5
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alphaK:  10000
TitanCNA_alphaR:  5000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores:  1
TitanCNA_mem:  16G
TitanCNA_runtime:  "300:00:00"
TitanCNA_pe: -pe smp 1 -binding linear:1  



